### ISSUE TITLE
Taxa de desistência não seria taxa de evasão acumulada?

### ISSUE THREAD

**Issue by masakik** [uspdev/datagrad#15]
e taxa de conclusão não seria taxa de conclusão acumulada?

**Comment by Potenho** [comment]
Sim. Todos são acumulados.

**Comment by masakik** [comment]
Então seria legal ajustar o nome no gráfico e na tabela.

**Comment by masakik** [comment]
Faltou a taxa de evasao acumulada.

**Comment by masakik** [comment]
Tambem, via de regra Taxa de evasão, sendo somente a primeira palavra maiuscula. As demais minúsculas.
